// Character generation script
const characters = [
    { name: 'janine', color: '#ff6b6b', story: ['Help! You found me!', 'The genie trapped me while I was just minding my own business!', 'I saw him capture so many others too...', 'There has to be a way to stop him!', 'Keep searching - I believe in you!'] },
    { name: 'emma', color: '#4ecdc4', story: ['Oh thank goodness, someone found me!', 'This nightmare started when I was just browsing the website...', 'The genie appeared and everything went dark!', 'I think he mentioned something about being vulnerable to certain things...', 'You need to find the others and piece this together!'] },
    { name: 'sophia', color: '#45b7d1', story: ['Finally! I was starting to lose hope!', 'That evil genie is terrifying - he trapped me here against my will!', 'I heard him talking to himself about some ancient weakness...', 'But he was very paranoid about it, like he was afraid someone would find out!', 'Please be careful and find the others!'] },
    { name: 'rabbi', color: '#96ceb4', story: ['My child, you have found me in this dark place...', 'The evil one speaks of powers beyond our understanding...', 'But remember, even the mightiest can fall to simple truths...', 'Seek wisdom in unexpected places...', 'May you find strength to free us all.'] },
    { name: 'dayne', color: '#feca57', story: ['Yo! Thank God you\'re here!', 'This genie dude is seriously messed up!', 'He was going on and on about how invincible he is...', 'But I swear I heard him freaking out about something earlier...', 'You gotta find everyone else - we\'re stronger together!'] },
    { name: 'shaindel', color: '#ff9ff3', story: ['Baruch Hashem, you found me!', 'This reshus is trying to keep us all trapped here!', 'I was davening when he appeared - such evil!', 'But I heard him mention something that scared him...', 'Keep looking for the others, we need to help each other!'] },
    { name: 'shmuel', color: '#54a0ff', story: ['Ah, finally someone comes!', 'This genie, he thinks he\'s so powerful...', 'But even the strongest have their achilles heel, no?', 'I noticed he gets very nervous about certain topics...', 'Find the others - together we\'ll figure this out!'] },
    { name: 'olivia', color: '#5f27cd', story: ['OMG you\'re here! I was so scared!', 'That genie is like, totally evil and creepy!', 'He kept bragging about his powers but then got all weird...', 'Like, he started mumbling about something that could hurt him?', 'You have to find everyone else and save us!'] },
    { name: 'jazz', color: '#00d2d3', story: ['Hey there! About time someone showed up!', 'This whole genie situation is wild, right?', 'He seems super confident but I caught him looking paranoid...', 'There\'s definitely something he\'s afraid of...', 'Go find the others - we need all the help we can get!'] },
    { name: 'nona', color: '#ff6348', story: ['Bubbeleh! You found your old Nona!', 'This terrible genie took me from my kitchen!', 'He was bragging about his powers while I was cooking...', 'But you know what? Every bully has something they\'re afraid of...', 'Find the others, darling - together we\'ll beat him!'] },
    { name: 'sabi', color: '#2ed573', story: ['אתה מצאת אותי! Thank you for finding me!', 'This genie thinks he\'s so strong...', 'But I served in the army - I know when someone is hiding fear...', 'He mentioned something that makes him weak...', 'Keep searching for the others - we\'ll figure this out!'] },
    { name: 'rona', color: '#ffa502', story: ['Finally! I\'ve been waiting forever!', 'This genie is absolutely horrible!', 'But I\'m observant, and I noticed something...', 'He gets really agitated when certain words are mentioned...', 'Find everyone else - maybe together we can solve this!'] },
    { name: 'gili', color: '#3742fa', story: ['You came! I knew someone would find us!', 'The genie trapped me while I was just living my life...', 'He seems all-powerful but I saw him flinch once...', 'Something scared him, but I couldn\'t tell what...', 'Keep looking - there are others who need help too!'] },
    { name: 'neta', color: '#2f3542', story: ['Thank goodness you\'re here!', 'This evil genie has been keeping us all prisoner!', 'I tried to escape but his magic is too strong...', 'However, I did notice he seems afraid of something...', 'Find the others - together we might find his weakness!'] },
    { name: 'gilad', color: '#ff3838', story: ['Bro! You actually found me!', 'This genie is seriously bad news...', 'He keeps talking about how nobody can stop him...', 'But earlier I heard him muttering about some weakness...', 'You need to find everyone else - safety in numbers!'] },
    { name: 'ishai', color: '#2ecc71', story: ['Hey! So glad you found me!', 'This genie situation is totally insane...', 'He acts all tough but I saw him get nervous about something...', 'There\'s definitely something he\'s hiding...', 'Keep searching - find all the others!'] },
    { name: 'yahav', color: '#e74c3c', story: ['You found me! I was starting to give up hope!', 'This evil genie came out of nowhere!', 'He was boasting about his powers but then got all paranoid...', 'I think there\'s something specific that he fears...', 'Please find the others - we need to work together!'] },
    { name: 'freya', color: '#9b59b6', story: ['Oh my! You actually made it here!', 'That dreadful genie trapped me in this awful place!', 'He seems invincible but I\'m sure there\'s a way...', 'Even the most powerful beings have vulnerabilities...', 'Do find the others, dear - we must help each other!'] },
    { name: 'mira', color: '#1abc9c', story: ['Thank you for finding me!', 'This genie is truly evil - he trapped us all!', 'But I\'ve been listening carefully to what he says...', 'There\'s something that makes him very afraid...', 'Find everyone else - maybe together we can defeat him!'] },
    { name: 'abby', color: '#f39c12', story: ['OMG finally! I thought I\'d be stuck forever!', 'This genie is like, the worst thing ever!', 'He keeps acting all powerful and scary...', 'But I noticed he gets really jumpy about certain things...', 'You have to find all the others - we need each other!'] },
    { name: 'sas', color: '#8e44ad', story: ['You made it! I was losing hope!', 'This evil genie has incredible powers...', 'But every powerful being has an achilles heel...', 'I sensed fear in him when certain topics came up...', 'Please find the others - we\'re stronger together!'] },
    { name: 'yeli', color: '#16a085', story: ['Finally someone found me!', 'This genie thinks he\'s invincible...', 'But I have a feeling there\'s something he\'s afraid of...', 'He got really agitated earlier about something...', 'Find everyone else - maybe together we can save ourselves!'] },
    { name: 'neshama', color: '#c0392b', story: ['Sweetie! You found me!', 'This terrible genie has us all trapped here...', 'But you know what? There\'s always hope...', 'Even the darkest forces have something they fear...', 'Find all the others, bubbeleh - together we\'ll find a way!'] }
];

// This script helps generate the remaining character pages
console.log('Characters to create:', characters.map(c => c.name).join(', '));